name: Publish Package

on:
  push:
    tags:
      - 'v*-*'


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate tag format
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if ! [[ $TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+-[0-9]{12}$ ]]; then
            echo "Invalid tag format. Expected format: vx.y.z-yyyymmddhhmm"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Generate client code
        run: npm run generate

      - name: Build
        run: npm run build

      - name: Update package version
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          npm version $TAG --no-git-tag-version

      - name: Publish to npm registry
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }} 
